AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  fiap-auth

Globals:
  Function:
    Timeout: 3

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      FunctionName: fiap-auth
      Environment:
        Variables:
          JWT_SECRET: !Ref JWTSecretParameter
          RDS_DATABASE: !Ref RDSDatabaseParameter
          RDS_HOSTNAME: !Ref RDSHostnameParameter
          RDS_PASSWORD: !Ref RDSPasswordParameter
          RDS_PORT: !Ref RDSPortParameter
          RDS_USERNAME: !Ref RDSUsernameParameter
      Architectures:
        - x86_64
      Events:
        Auth:
          Type: Api
          Properties:
            Path: /auth
            Method: post

Parameters:
  JWTSecretParameter:
    Type: String
    Default: ""

  RDSDatabaseParameter:
    Type: String
    Default: ""

  RDSHostnameParameter:
    Type: String
    Default: ""

  RDSPasswordParameter:
    Type: String
    Default: ""

  RDSPortParameter:
    Type: Number
    Default: "3306"

  RDSUsernameParameter:
    Type: String
    Default: ""

Outputs:
  FiapAuthApi:
    Description: "API Gateway endpoint URL for Prod stage for fiap auth function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fiap-auth/"
  FiapAuthFunction:
    Description: Fiap Auth Lambda Function ARN"
    Value: !GetAtt FiapAuthFunction.Arn
  FiapAuthFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt FiapAuthFunctionRole.Arn
