name: Deploy and update lambda

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '18.*'

      - name: Install Node.js dependencies
        run: npm install

      - name: Set Environment Variables
        run: |
          echo 'export JWT_SECRET=valor_1' >> $GITHUB_ENV

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_NODE_ENV: "production"
          envkey_TZ: "America/São Paulo"
          envkey_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          envkey_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_RDS_DATABASE: ${{ vars.RDS_DATABASE }}
          envkey_RDS_HOSTNAME: ${{ vars.RDS_HOST }}
          envkey_RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          envkey_RDS_PORT: ${{ secrets.RDS_PORT }}
          envkey_RDS_USERNAME: ${{ secrets.RDS_USER }}

      - name: Zip package
        run: zip -j -r lambda.zip .

      - name: Deploy the app
        run: aws lambda update-function-code --function-name="fiap-auth" --zip-file=fileb://lambda.zip
